[package]
name = "jdpub"
description = "Annotate source documents with Japanese readings and definitions."
version = "0.7.1"
edition = "2024"
authors = ["hachha <hachha@hachha.dev>"]
keywords = ["japanese", "language", "ebook", "epub"]
categories = []
repository = "https://github.com/HarrisonHall/jdpub"
homepage = "https://github.com/HarrisonHall/jdpub"
license-file = "LICENSE"
readme = "README.md"
rust-version = "1.85.0"

[features]
default = []
jp = ["dep:jmdict-fast"]

[dependencies]

color-eyre = "0.6"

futures = "0.3"
reqwest = { version = "0.12", features = ["rustls-tls"], default-features = false }
tokio = { version = "1.47", features = ["sync", "rt", "rt-multi-thread", "macros", "process", "signal"] }
tokio-stream = "0.1"
tokio-util = "0.7"

# Logging:
colored = "3.1"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-test = "0.2"

durf_parser = "0.2"


# Lang
charabia = { version = "0.9.9", default-features = false, features = ["japanese"] }
jmdict-fast = { version = "0.1.1", optional = true }
wana_kana = "4.0.0"

# jlpt
csv = "1.4"
serde = { version = "1", features = ["derive"] }

# HTML
build_html = "2.7"
uuid = { version = "1.19", features = ["v4"] }

# EPUB
epub-builder = "0.8"
epub-parser = "0.2"

# File
rust-embed = { version = "8.11", features = ["include-exclude", "compression"] }
clap = { version = "4.5", features = ["derive"] }
toml = "0.9"

# Util
shellexpand = "3.1"
